---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: audio-dev-workstation
# description will be included in the image's metadata
description: personal audio and ai dev workstation build

alt-tags:
  - dev
  - iso

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module

stages:
  - name: bluebuild
    from: docker.io/library/rust:1.77
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - secureblue/bubblejail
        - arrobbins/JDSP4Linux
    install:
      allow-erasing: true
      packages:
        - nodejs
        - ripgrep
        - rpmrebuild
        - rkhunter
        - bubblejail
        - pipewire-module-filter-chain-lv2
        - pipewire-config-rates
        - lsp-plugins-lv2
        - Carla
        - JamesDSP
        - Carla-vst
        - lv2-carla
        - irqbalance
        - realtime-setup
        - realtime-tests
        - tuned-profiles-compat
        - tuned-profiles-realtime
        - rtirq
        - vivaldi-stable
        - 1password
        - 1password-cli
        - steam-devices
      exclude:
        - steam

  # set some realtime kernel arguments
  - type: kargs
    kargs:
      - threadirqs
      - preempt=full

  # custom justfiles
  - type: justfiles
    validate: true
    include:
      - rt-group.just
      - fix-bazaar.just
      - install-bun-docker.just
      - install-bun-scary.just
      - install-discord.just

  - type: dnf
    repos:
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      files:
        - https://packages.microsoft.com/config/rhel/9/prod.repo
    install:
      packages:
        - powershell

  - type: systemd
    system:
      enabled:
        - rtirq.service
        - tuned.service
      disabled:
        - NetworkManager-wait-online.service
        - cpupower.service    # incompatible with tuned

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
