---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: audio-dev-workstaion
# description will be included in the image's metadata
description: personal audio and ai dev workstation build

alt-tags:
  - dev
  - iso

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    replace:
    - repo: fedora
      packages:
        old: pipewire-config-raop
        new: pipewire-config-rates

  - type: dnf
    repos:
      copr:
        - atim/starship
        - secureblue/bubblejail
    install:
      packages:
        - bubblejail
        - pipewire-module-filter-chain-lv2
        - lsp-plugins-lv2
        - Carla-vst
        - lv2-carla
        - realtime-setup
        - rtirq
        - realtime-tests
        - tuned
        - tuned-profiles-compat
        - vivaldi-stable
        - 1password
        - 1password-cli
        - rpmrebuild
        - ripgrep

  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/config/rhel/9/prod.repo
    install:
      packages:
        - powershell

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        # If no repo information is specified, Flathub will be used by default
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub (system)
        install:
          - studio.kx.carla
          - me.timschneeberger.jdsp4linux

  - type: systemd
    system:
      enabled:
        - rtirq.service
        - tuned.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
