---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: audio-dev-workstation
# description will be included in the image's metadata
description: personal audio and ai dev workstation build

alt-tags:
  - dev
  - iso

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module

stages:
  - name: bluebuild
    from: docker.io/library/rust:1.77
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/*
  
  # set some realtime-supporting kernel arguments
  - type: kargs
    kargs:
      - threadirqs
      - preempt=full
  
  # base/general install stage
  - type: dnf
    repos:
      copr:
        - atim/starship
        - secureblue/bubblejail
    install:
      allow-erasing: true
      packages:
      # base and security
        - ripgrep
        - rpmrebuild
        - rkhunter
        - bubblejail
#######vvv TESTING AND DEV ONLY vvv#######
#######vvvv REMOVE BEFORE PROD vvvv#######
        - nodejs
#######^^^ TESTING AND DEV ONLY ^^^########
#######^^^^ REMOVE BEFORE PROD ^^^^########
      # high-integeration desktop apps
        - vivaldi-stable
        - 1password
        - 1password-cli

# audio toolchain installs
  - type: dnf
    install:
      allow-erasing: true
      packages:
      # audio toolchain
        - pipewire-plugin-jack
        - pipewire-config-rates
        - lv2
        - pipewire-module-filter-chain-lv2
        - lsp-plugins-lv2
        - lv2-x42-plugins
        #- Carla
        #- Carla-vst
        - lv2-carla
        - raysession
      # realtime priority
        - rtirq
        - rtkit
        - tuned-profiles-compat
        - tuned-profiles-realtime
        - tuned-profiles-cpu-partitioning
        - tuned-profiles-atomic
        - realtime-tests
      exclude:
        - steam

# steam controller handler, leave steam itself to flathub
  - type: dnf
    install:
      allow-erasing: true
      packages:
        - steam-devices
      exclude:
        - steam

  # custom justfiles
  - type: justfiles
    validate: true
    include:
      - fix-bazaar.just
      - install-bun.just
      - install-discord.just
      - setup-vivaldi.just

  - type: dnf
    repos:
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      files:
        - https://packages.microsoft.com/config/rhel/9/prod.repo
    install:
      packages:
        - powershell

  - type: systemd
    system:
      enabled:
        - rtirq.service
        - rtkit-daemon.service
        - tuned.service
        - tuned-ppd.service
      disabled:
        - NetworkManager-wait-online.service
        - cpupower.service    # incompatible with tuned

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
